import type { Metadata } from "next";
import { Sora, Source_Code_Pro, Space_Grotesk } from "next/font/google";
import "./globals.css";
import ButtonGradient from "../assets/svg/ButtonGradient";

const sora = Sora({ subsets: ["latin"] });
const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  variable: "--font-code",
});
const grotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-grotesk",
});

export const metadata: Metadata = {
  title: "Brainwave",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.className} ${sourceCodePro.variable} ${grotesk.variable} dark`}
      >
        {children}

        <ButtonGradient />
      </body>
    </html>
  );
}
